
---
title: "Introduction to cbsots"
author: "Rob van Harrevelt"
date: '`r Sys.Date()`'
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
linkcolor: blue    
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Introduction to regts}
-->

\newcommand{\longerpage}[1][1]{\enlargethispage{#1\baselineskip}}
\newcommand{\shorterpage}[1][1]{\enlargethispage{-#1\baselineskip}}
\newcommand{\needlines}[1]{\Needspace{#1\baselineskip}}


```{r echo = FALSE, message = FALSE}
# input/output chunks are separated
# R inputlines start with >, outputlines with nothing
knitr::opts_chunk$set(collapse = FALSE, comment = "", prompt = TRUE)

# set options for page width = 100
options(width = 100)
```

# Introduction


# Example

```{r}
library(cbsodataR)

data <- cbs_get_data(id = "70076NED", Perioden = has_substring("2000KW"),
                     GoederenEnDiensten = c("      2005", "      3000"),
                     select = c("Perioden", "GoederenEnDiensten", "Volumemutaties_1", "Waardemutaties_4"))
print(data)

library(cbsots)
edit_ts_code("testje.rds")
```